
# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS EN LA NUBE (AZURE)
# ===================================================================

# 1. URL de conexión a Azure (Se crea la BD automáticamente si no existe)
spring.datasource.url=jdbc:mysql://pats-server-itess-2026.mysql.database.azure.com:3306/pats_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true&requireSSL=false

# 2. Tu usuario administrador de Azure (el que definiste en el formulario)
spring.datasource.username=patsadmin

# 3. Tu contraseña de Azure
spring.datasource.password=Pats2026

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forzamos el uso del dialecto correcto para MySQL 8 en Azure
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR BACKEND
# ===================================================================
server.port=8080