
# ===================================================================
# CONFIGURACI�N DE LA BASE DE DATOS EN LA NUBE (AZURE)
# ===================================================================

# 1. URL de conexi�n a Azure (Se crea la BD autom�ticamente si no existe)
spring.datasource.url=jdbc:mysql://pats-server-itess-2026.mysql.database.azure.com:3306/pats_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true&requireSSL=false

# 2. Tu usuario administrador de Azure (el que definiste en el formulario)
spring.datasource.username=patsadmin

# 3. Tu contrase�a de Azure
spring.datasource.password=Pats2026

# ===================================================================
# CONFIGURACI�N DE HIBERNATE / JPA
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forzamos el uso del dialecto correcto para MySQL 8 en Azure
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===================================================================
# CONFIGURACI�N DEL SERVIDOR BACKEND
# ===================================================================
server.port=8080

# CONFIGURACION DE SUBIDA DE ARCHIVOS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB