spring.application.name=backend

# Configuraci�n de la URL de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/pats_db?serverTimezone=UTC
# Tu usuario de MySQL (por defecto suele ser root)
spring.datasource.username=root
# Tu contrase�a de MySQL
spring.datasource.password=?????

# Configuraci�n de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor backend
server.port=8080